### ISSUE TITLE
Foundation version

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyoes#10]
I think we're currently still using Foundation 5.3.0 which came out june 2014.

Can we upgrade to the latest version (5.5.1), or are there too many libsass problems waiting there? If 5.5 is not possible, can we go to 5.4.x?

/cc @taeymma

**Comment by kmillet** [comment]
Maarten heeft dat daarnet gefixt. Incompatibiliteit tussen sass en foundation is blijkbaar gefixt.

**Comment by koenedaele** [comment]
I'm assuming this is no longer an issue and closing it.
