### ISSUE TITLE
dayfirst=False zetten in utils

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/pyoes#100]
Zie https://github.com/OnroerendErfgoed/meldingen_vooronderzoek/issues/339

**Comment by BartSaelen** [comment]
Ook zorgen dat `None` values genegeerd worden

**Comment by koenedaele** [comment]
Gelieve dat goed te bekijken. Die dayFirst zal er wel met een reden ingekomen zijn, waarschijnlijk parsen we (of hebben we dat gedaan) ergens strings van het genre "04-12-2004". Wat niet meer correct zal werken als je die dayFirst afzet.

**Comment by BartSaelen** [comment]
Ja het werkt nu ook niet @koenedaele want we geven strings als "2017-11-12" door en die zijn dan ook niet juist.

**Comment by koenedaele** [comment]
Klopt. Maar nu draaien we de zaak om waardoor het mogelijk ergens anders niet meer gaat werken. Nu, dan moeten we maar voor onszelf duidelijk stellen dat we altijd "jaar-maand-dag" moeten doorgeven aan deze functie.

Een cast van Date naar Datetime lijkt me nog altijd zinnig trouwens. Dat zal ook al wat fouten voorkomen.
