### ISSUE TITLE
macros.jinja wordt niet gevonden

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#103]
In https://github.com/OnroerendErfgoed/pyoes/blob/master/pyoes/templates/pyoes/layout.jinja2#L62 wordt `from 'macros.jinja2' import ga_tracker` ingeladen om later deze functie te gebruiken.

Op dit moment lukt deze import niet. Niet pyoes/macros.jinja wordt geimporteerd maar wel het macros bestand uit de app die pyoes gebruikt.

Voorlopige oplossing is om de code uit pyoes/macros.jinja te kopieëren naar app/macros.jinja maar zo creëren we een hoop dubbele code. bv https://github.com/OnroerendErfgoed/notas/blob/master/notas/templates/macros.jinja2#L1

Of kan dit simpelweg opgelost worden door een instelling te gebruiken in onze app dat de juiste macro.jinja wordt gebruikt?

**Comment by BartSaelen** [comment]
@taeymma kan je dit eens bekijken?
