### ISSUE TITLE
Privacybeleid link in footer

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/pyoes#116]
@koenedaele zet je hier de nodige info? waar de link naar moet verwijzen, en layout?

**Comment by cedrikv** [comment]
Aanzet:
![image](https://user-images.githubusercontent.com/1849458/42079750-cbbaf124-7b80-11e8-83be-edfb20545dd0.png)

reply:

> ik denk dat die beter op een aparte regel komt te staan. De link gaat naar
> https://www.onroerenderfgoed.be/nl/over-ons/privacybeleid/

**Comment by koenedaele** [comment]
Ziet er goed uit. :+1:
