### ISSUE TITLE
pyoes_0.3.0 scaffold set wrong app  package

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyoes#14]
Currently app package is set to "pyoes". This should be set at scaffolding to the name of the package it's being scaffolded in (eg. besluiten or beheersplannen).

**Comment by taeymma** [comment]
This is only usefull for new applications, existing applications allready have a layout.jinja2 which will not be overwritten by the scaffold.
Generic app_package added to layout file for new applications.
