### ISSUE TITLE
input[type="email"] zelfde stijl als input[type="text"] maken

### ISSUE THREAD

**Issue by JonasGe** [OnroerendErfgoed/pyoes#153]
Deze lijn toevoegen op lijn 9 van `_oe-forms.scss`:

`.placeholder-container input[type="email"] { border: none !important; box-shadow: none; margin: 0; display: table-cell; background-color: transparent !important; color:$dark-gray; }
`

**Comment by cedrikv** [comment]
ik zou ook eens gans de code cecken op "input[type="text"] " en kijken of het nodig is om daar de "email" ook bij te zetten.

**Comment by JonasGe** [comment]
> ik zou ook eens gans de code cecken op "input[type="text"] " en kijken of het nodig is om daar de "email" ook bij te zetten.

Dat specifiek type niet. Ik heb het versimpeld naar `input`, dat was wel nodig.
