### ISSUE TITLE
Cookie banner toevoegen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/pyoes#190]
De tekst vraag ik nog op.

![image](https://user-images.githubusercontent.com/1850704/108482024-3930e300-7299-11eb-8368-f1c2b9a77495.png)

Voorlopig misschien doen zoals op de corporate site met een banner onderaan.

Scope:

- consent vragen aan gebruiker
- indien geen consent niets tracken met GA

**Comment by cedrikv** [comment]
Geen we dit per applicatie vragen? dus voor elke app moet er toestemming komen? of bvb alles voor archeologieportaal valt onder zelfde "toestemming".

**Comment by claeyswo** [comment]
Good point, ik zou het per app doen?

**Comment by koenedaele** [comment]
Vanuit het standpunt van een gebruiker is het archeologieportaal één app. Liefst daar niet voor elk onderdeel consent vragen of mensen komen helemaal zot. Kunnen we ook oplossen door alle toepassingen samen te voegen tot één

**Comment by goessebr** [comment]
@claeyswo, is er al een update over de tekst?

**Comment by cedrikv** [comment]
Hmm, @claeyswo ik bedenk me net dat die tekst nog licht moest worden gewijzigd:

> Het agentschap Onroerend Erfgoed gebruikt cookies om de goede werking van onze website te verzekeren en jouw surfervaring te verbeteren. Meer informatie over de cookies die we gebruiken lees je in ons cookiebeleid. Voor het gebruik van sociale media cookies hebben wij jouw toestemming nodig. Deze cookies gebruiken we om sociale media, zoals Facebook, Twitter of YouTube, te linken aan onze website. Zo kan je bijvoorbeeld artikels delen op sociale media of bepaalde inhoud van die sites op deze website bekijken. Wil je hiervan kunnen genieten?

Wat waren de changes weer?
