### ISSUE TITLE
footer not sticking to bottom of page

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/pyoes#21]
footer floats under the last panel in the page.. not fixed at bottom.

**Comment by cedrikv** [comment]
seems not ok in beheersplannen:
![screenshot from 2015-03-02 14 13 29](https://cloud.githubusercontent.com/assets/1849458/6441260/651bddbe-c0e6-11e4-9223-f2c4799c650e.png)

**Comment by cedrikv** [comment]
ok after update pyoes scaffold
