### ISSUE TITLE
Header is nog niet goed

### ISSUE THREAD

**Issue by JonasGe** [OnroerendErfgoed/pyoes#249]
Zie https://github.com/OnroerendErfgoed/rapporten_archeologie/issues/748

Op mijn scherm (2560 × 1600) geen probleem tot ik uitzoom tot -75%, dan krijg ik hetzelfde probleem dat Jolijn toont in dat ticket.

**Comment by roefem** [comment]
https://github.com/OnroerendErfgoed/rapporten_archeologie/issues/748#issuecomment-1313677528
