### ISSUE TITLE
Pyoes kan niet meer standalone gerund worden

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/pyoes#25]
Als je pyoes probeert te runnen als stand alone app via pserve en browst naar http://0.0.0.0:6555/, krijg je een error:
UndefinedError: 'pyramid.request.Request object' has no attribute 'user'
Probleem zit in:
/home/vandece/PycharmProjects/pyoes/pyoes/templates/pyoes/header.jinja2
op:
{% set login_user = login_user|default(request.user.userid) -%}

**Comment by koenedaele** [comment]
Means that it's by default assuming that pyramid_oeauth is being used.

I think that call would be the same as pyramid.security.unauthenticated_userid(request), but I'm not sure you can call a function like that from a Jinja2 template.

**Comment by koenedaele** [comment]
As I assumed, you can not easily call python functions from templates.

I can think of a few clean ways to handle this:

* According to http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/templates.html#renderer-system-values you should be able to use "renderer globals" to define extra values that will be passed on to every template rendered.
* Create a filter that does something like "return request.user.userid if user in request else unauthenticated_userid(request)" and add that to the filters.

I think the second options is the cleanest and pollutes the template variable space the least and should work both with pyramid_oeauth and regular pyramid.

**Comment by cedrikv** [comment]
The front end is fixed so it doesn't asks for a user id when not the user is not logged in.
Clean backend solution can still be implemented, but is the bug not blocking anymore.

**Comment by taeymma** [comment]
pyramid.security.unauthenticated_userid(request) is deprecated.
Replacement function is available in the Request object, so no need to call a python function. (http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.authenticated_userid)
