### ISSUE TITLE
Remove bower_components from git

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/pyoes#29]
Is there a reason to check the javascript libraries (handled by bower) in in git?
https://github.com/OnroerendErfgoed/pyoes/tree/master/pyoes/static/bower_components

**Comment by kmillet** [comment]
Dit lijkt me inderdaad niet nodig. Ik weet niet of @koenedaele dit zo bedoeld heeft?

**Comment by koenedaele** [comment]
I think I added those to the repository so people could check out the code and run the demo without needing to install npm, grunt, bower, ... (the entire client side javascript toolchain).

As far as I'm concerned, they can be removed, but the installation instructions should be probably be updated in that case.

It might also be helpful to create some kind of prepare command and a demo scaffold, similar to what Atramhasis has. In that way, we could download all dependencies prior to release on pypi and package them with pyoes.

Getting a look at the heritage styles and templates could then be a simple case of:

* mkvirtualenv pyoes
* pip install pyoes (installs latest version from pypi)
* pcreate pyoes_demo
* pserve development.ini
