### ISSUE TITLE
Probleem met favicon.ico

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/pyoes#30]
@koenedaele 
@kmillet 
@cahytinne 

Opgemerkt in de herkenningstekens, door de favicon.ico static view probeert hij die file op te halen in de static folder van pyoes. Er zit echter een recursive-exclude op de static folder dus ik snap niet hoe dit ooit kan werken. Wat is eigenlijk de gedachte achter werken met een static view ipv gewoon te serven in de static folder?

**Comment by koenedaele** [comment]
See http://pyramid-cookbook.readthedocs.org/en/latest/static_assets/files.html#serving-a-single-file-from-the-root

Without the static view you cannot host favicon.ico in the root of the website. I know that nowadays there are ways of specifying where the favicon can be found (ie. in /static/favicon.ico), but this stll has some disadvantages (eg. http://stackoverflow.com/questions/21359342/is-putting-your-favicon-ico-file-in-a-non-root-path-a-bad-idea).

For something like robots.txt there's generally no choice.

Currently not sure why it used to work and doesn't anymore now.

**Comment by claeyswo** [comment]
At that point in time the manifest contained:

```
recursive-include pyoes/static *
recursive-exclude pyoes/static/.sass-cache *
```

So the favicon.ico was bundled with pyoes. Simple solution would be to add an exception to this rule for favicon.ico but I don't know the project well enough to judge if this is a viable solution.

**Comment by taeymma** [comment]
solved
added to manifest.ini:

include pyoes/static/favicon.ico
