### ISSUE TITLE
Create a generic 404

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyoes#31]
Create a generic 404 Error template.

Should be something nice (like https://github.com/404) that tells people that although we didn't find what they were looking for, they could try something else (more along the lines of https://inventaris.onroerenderfgoed.be/404).

**Comment by taeymma** [comment]
Generic template added to pyoes. Still has to be restyled.

**Comment by BartSaelen** [comment]
@taeymma deze is gesloten op jira, hier ook sluiten?

**Comment by taeymma** [comment]
Generic pagina's zijn toegevoegd aan pyoes, maar deze hebben nog geen nieuwe stijl of tekst gekregen.

**Comment by koenedaele** [comment]
@taeymma @TOM-VC 

Deze staat nu al maanden open. Kan dit eens afgesloten worden?

**Comment by kmillet** [comment]
Werd al een tijd terug gevraagd aan communicatie om tekstjes aan te leveren. Zal besproken worden vanochtend tijdens vergadering met communicatie.

**Comment by TOM-VC** [comment]
Margot en Natalie gaan dit ( teksten ) verder opnemen en afwerken.



Op 13-nov.-2015, om 09:58 heeft Klaas Millet <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Werd al een tijd terug gevraagd aan communicatie om tekstjes aan te leveren. Zal besproken worden vanochtend tijdens vergadering met communicatie.

**Comment by kmillet** [comment]
Hierbij het tekstje:

Fout 404  De pagina werd niet gevonden

De pagina die je hebt opgevraagd, bestaat niet (meer). Wat nu?
Ben je zeker dat je een correcte URL hebt ingegeven?
Ben je op deze foutpagina terechtgekomen na het volgen van een link op onze site?
Of ben je van mening dat deze pagina wel zou moeten bestaan?
Neem dan contact met ons op. Vergeet niet te vermelden welke pagina je zocht.
