### ISSUE TITLE
Create a generic 500

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyoes#32]
Create a generic "sorry, something went wrong. It's not your fault!" template.

**Comment by taeymma** [comment]
Generic template added to pyoes. Still has to be restyled.

**Comment by BartSaelen** [comment]
@taeymma deze is gesloten op jira, hier ook sluiten?

**Comment by taeymma** [comment]
zelfde als #31

**Comment by koenedaele** [comment]
@taeymma @TOM-VC 

Deze staat nu al maanden open. Kan dit eens afgesloten worden?

**Comment by kmillet** [comment]
Tom, kan je deze tekst gebruiken?

Fout 500 - Er is een  technisch probleem
Pech! Onze website heeft een technisch probleem. Hierdoor kan je de gevraagde pagina op dit ogenblik niet raadplegen.  Contacteer ons om dit probleem te melden.  Vergeet niet te vermelden welke pagina je zocht.

**Comment by TOM-VC** [comment]
Dag Klaas,
Ik leg het voor aan communicatie morgen
Ze moeten de toon van de boodschap bepalen.
Pech lijkt me nogal cru :-)

Groet Tom




Op 23-nov.-2015, om 14:12 heeft Klaas Millet <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Tom, kan je deze tekst gebruiken?

Fout 500 - Er is een technisch probleem
Pech! Onze website heeft een technisch probleem. Hierdoor kan je de gevraagde pagina op dit ogenblik niet raadplegen. Contacteer ons om dit probleem te melden. Vergeet niet te vermelden welke pagina je zocht.

**Comment by kmillet** [comment]
Dag Tom,

dat is wat ik teruggekregen heb van communicatie. Maar je kan het altijd nog eens afpoetsen, zolang het niet te lang meer aansleept :).

**Comment by TOM-VC** [comment]
ok ik kleef het al in een dummy pagina en verstuur nu een mail naar Natalie

Op 23-nov.-2015, om 14:39 heeft Klaas Millet <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Dag Tom,

dat is wat ik teruggekregen heb van communicatie. Maar je kan het altijd nog eens afpoetsen, zolang het niet te lang meer aansleept :).
