### ISSUE TITLE
Use minified foundation

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyoes#33]
Currently the layout.jinja2 template loads /static/bower_components/foundation/js/foundation.js. Better would be to load /static/bower_components/foundation/js/foundation.min.js. At least in production. Maybe check a settings for things, ie. if `pyoes.debug_js` is True, load the normal versions, else the minified ones.

**Comment by taeymma** [comment]
I think we can use the minified version in development also. I see no reason why the full js should be loaded.

**Comment by koenedaele** [comment]
I believe with dojo we use the non-minified version for easier debugging in debug mode. If that's not relevant here, I'm fine with always using the minified version.
