### ISSUE TITLE
Add datetime_format_filter

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyoes#37]
There's a datetime_format_filter in adviezen that's also present in besluiten and beheersplannen. Please add this as a generic filter to pyoes and refacor those apps to use the pyoes filter and not a local version.

**Comment by taeymma** [comment]
This is a jinja2 filter.. 

jinja2.filters =
        datetimeformat = adviezen.utils.datetime_format_filter

in development.ini.
Is a macro really necessary?
@koenedaele

**Comment by koenedaele** [comment]
Are you mixing two tickets?

In adviezen, besluiten and beheersplannen this filter is defined. So, we have it in 3 places. It would be better to just have it in pyoes and just use the following declaration:

```ini
jinja2.filters =
datetimeformat = pyoes.utils.datetime_format_filter
```

If there's a standard filter in jinja2 nowadays, that we can use, that would be fine as well.

**Comment by taeymma** [comment]
I was idd confused with an other ticket.
