### ISSUE TITLE
Profiel menu zou omschrijving moeten bevatten i.p.v. username

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/pyoes#38]
Voor internen valt dit nog mee maar externen krijgen iets te zien van de vorm 'bJwz4qqSvfcIpGjcvcG_7g'.

Op te halen uit ```request.user.actor.omschrijving``` indien ```request.user.actor``` bestaat anders de default van ```request.userid```.

**Comment by claeyswo** [comment]
@taeymma Kan jij hier eens naar kijken? Zou leuk zijn moest dit ook nog kunnen meegaan met de adviezen.

**Comment by taeymma** [comment]
Dit zit momenteel niet in pyoes. Ik zal het voorlopig aanpassen adviezen en nieuwe issue aanmaken in pyoes voor generieke profiel pagina.

**Comment by taeymma** [comment]
cfr #39
