### ISSUE TITLE
Is de typekit import nog nodig?

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/pyoes#53]
https://github.com/OnroerendErfgoed/pyoes/blob/3f83d0b7d0428d327fa8baaf0e947a3a08c1083b/pyoes/templates/pyoes/layout.jinja2#L33

Nu we onze eigen font gebruiken

@TOM-VC @taeymma

**Comment by koenedaele** [comment]
Waarschijnlijk niet. Betalen we daar eigenlijk nog altijd voor? @maarten-vermeyen

**Comment by koenedaele** [comment]
Ik zou ze er in elk geval uitgooien. Is alleen maar een netwerkrequest die bandbreedte opeet.

**Comment by taeymma** [comment]
fixed in #62
