### ISSUE TITLE
Aanpassen tekst footer

### ISSUE THREAD

**Issue by maarten-vermeyen** [OnroerendErfgoed/pyoes#59]
Hierbij de definitieve tekst voor zowel de website als andere applicaties:
 
Vlaanderen is erfgoed. Samen met onze partners maken we de zorg voor onroerend erfgoed voor iedereen vanzelfsprekend om Vlaanderen nu en straks mee vorm en kleur te geven. Onroerend erfgoed zijn zowel bouwkundig, archeologisch, landschappelijk, heraldisch als varend erfgoed.
 
(onroerenderfgoed.be is een officiële website van de Vlaamse overheid)= naam applicatie is een …
Uitgegeven door het agentschap Onroerend Erfgoed

**Comment by koenedaele** [comment]
@taeymma Kan dit al doorgevoerd worden in de nieuwe versie van het geoportaal? Komt dit mee met pyoes of is dit gekopieerd in de toepassing?

**Comment by taeymma** [comment]
Dat tekstje kunnen wij niet aanpassen. In de mobiele versie van geoportaal kan het wel aangepast worden aangezien dit een 'nagemaakte' vlaanderen banner is.

**Comment by taeymma** [comment]
Dit is aangepast door merkenbeleid. Footer toont nu het nieuwe tekstje.
