### ISSUE TITLE
verschillen in layout error pagina's

### ISSUE THREAD

**Issue by TOM-VC** [OnroerendErfgoed/pyoes#68]
bvb loket
https://dev-loket.onroerenderfgoed.be/oauth?goto=/archeologie&oauth_token=9821d3fdac6146d8929264d9e486b487&oauth_verifier=468b8c5ae92645f483bd5f002f337af9

https://dev-loket.onroerenderfgoed.be/archeologie/vondstmeldingen/formulier

lay out vb te vinden in de styleguide

De tekst is te lang in dit voorbeeld. Plaats een break voor 'Heb je net geprobeerd ....' en eventueel voor 'Dan was je ...'
<img width="1372" alt="schermafbeelding 2016-04-05 om 10 05 22" src="https://cloud.githubusercontent.com/assets/9110224/14275242/66440372-fb16-11e5-89d0-7e6ab479b0a8.png">

**Comment by taeymma** [comment]
surround me <div class="large-12 columns"> zou het ook moeten oplossen denk ik ;)

**Comment by TOM-VC** [comment]
klopt
maar een <br> is minder code

**Comment by taeymma** [comment]
< br > lost het probleem niet op op kleine schermen ;)
