### ISSUE TITLE
Logo in banner

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#76]
Ref. Opmerkingen in https://github.com/OnroerendErfgoed/erkenningen/issues/22 over website erkenningen.onroerenderfgoed.be

@kmillet, wijs jij ticket toe aan correcte persoon?

Logo in banner: moet ‘Leeuw\Vlaanderen is erfgoed’ zijn (niet Onroerend Erfgoed)

**Comment by taeymma** [comment]
In orde in nieuwe versie pyoes

**Comment by taeymma** [comment]
refs https://github.com/OnroerendErfgoed/erkenningen/issues/27
