### ISSUE TITLE
link voorzien naar de corporate website

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#77]
Ref. Opmerkingen in OnroerendErfgoed/erkenningen#22 over website erkenningen.onroerenderfgoed.be

@kmillet, wijs jij ticket toe aan correcte persoon?

Rechtsboven een link voorzien naar de corporate website

**Comment by taeymma** [comment]
Deze link is overlaatst speciaal weggehaald geweest. Moet deze nu terug komen @kmillet?

**Comment by kmillet** [comment]
Ga daar eens over overleggen met communicatie. Laat ze voorlopig nog weg dan.

**Comment by taeymma** [comment]
Er staat een onclick van het ergoed logo naar de corporate website ook normaal..

**Comment by taeymma** [comment]
De link van het logo is instelbaar met 
> {% set home_link = 'http://www.onroerenderfgoed.be/' %}

**Comment by kmillet** [comment]
@goessebr net nog eens nagevraagd. Het is ook goed als het logo correct doorverwijst naar Onroerend Erfgoed. Kan je dit aanpassen?

**Comment by goessebr** [comment]
Aangepast in https://github.com/OnroerendErfgoed/erkenningen/commit/89d04fc834746cf2bf26aa852919fb2ec561ddb6
