### ISSUE TITLE
sociale media

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#78]
Ref. Opmerkingen in OnroerendErfgoed/erkenningen#22 over website erkenningen.onroerenderfgoed.be

@kmillet, wijs jij ticket toe aan correcte persoon?

Het is een goed idee om rechts onderaan naar onze verschillende sociale media te verwijzen.

**Comment by kmillet** [comment]
zie Contacteer ons op https://www.onroerenderfgoed.be

**Comment by taeymma** [comment]
Zit in nieuwe versie van pyoes

**Comment by taeymma** [comment]
refs https://github.com/OnroerendErfgoed/erkenningen/issues/27
