### ISSUE TITLE
Favicon aanpassen

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#79]
Ref. Opmerkingen in OnroerendErfgoed/erkenningen#22 over website erkenningen.onroerenderfgoed.be

@kmillet, wijs jij ticket toe aan correcte persoon?

Favicon: leeuwtje ipv oude druppel http://webstijlgids.vlaanderen.be/element/favicon

**Comment by taeymma** [comment]
uitrollen nieuwe versie pyoes fixed dit probleem.

**Comment by taeymma** [comment]
refs https://github.com/OnroerendErfgoed/erkenningen/issues/27

**Comment by cedrikv** [comment]
precies nog niet in orde?

**Comment by taeymma** [comment]
Fixed in DEV
