### ISSUE TITLE
Margins headers en footers

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#80]
Ref. Opmerkingen in OnroerendErfgoed/erkenningen#22 over website erkenningen.onroerenderfgoed.be

@kmillet, wijs jij ticket toe aan correcte persoon?

Margins van global header en footer: Tom heeft een tijd geleden gevraagd aan Informatie Vlaanderen hoe de uitlijning van de global header en footer aangepast kon worden aan de deelsites. De tekst in de header en footer stond niet altijd gelijk uitgelijnd met de tekst in de body van de website, wat we net willen. De uitleg hierover vind je in het mailtje in de bijlage.

**Comment by kmillet** [comment]
de mail:

>  Als bijlage stuur ik twee stukjes css door die je kan toevoegen aan jouw globale css-file. Hiermee kan je de margins aanpassen van de Global header en footer zodat die aligneren met jouw ontwerp.
>  
> Onze global header en footer zitten op een vaste grid, vandaar jij beter de aanpassing doet vanuit je applicatie. Het geeft je ook de mogelijkheid om voor verschillende applicaties of websites waarbij jullie gebruik maken van dezelfde global header en footer de marges per site aan te passen, in het geval die niet allemaal exact dezelfde grid gebruiken.

@taeymma ik forward je de bijlagen

**Comment by taeymma** [comment]
Is al in orde als ik mij niet vergis?

**Comment by taeymma** [comment]
refs https://github.com/OnroerendErfgoed/erkenningen/issues/27

**Comment by taeymma** [comment]
Geleverde CSS veranderd niets aan header/footer inspringing.. maakt het alleen maar erger.

**Comment by taeymma** [comment]
Check, opgelost in erkenningen, zal code terugkoppelen naar pyoes.
Al een idee of die banners veranderen? refs #81
