### ISSUE TITLE
Global header en footer

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/pyoes#81]
Ref. Opmerkingen in OnroerendErfgoed/erkenningen#22 over website erkenningen.onroerenderfgoed.be

@kmillet, wijs jij ticket toe aan correcte persoon?

Global header en footer (zwarte balk): de embed codes hiervoor vind je hieronder

```
Type: Header 
ID: 5499d8dc0848446e91022c6dba9db343
Embed code: <script type="text/javascript" src="//widgets.vlaanderen.be/widget/live/5499d8dc0848446e91022c6dba9db343?mtime=1421237274"></script>

Type: Footer
ID: 79a9f632dc8e45aa884f7924ee16f7bf
Embed code: <script type="text/javascript" src="//widgets.vlaanderen.be/widget/live/79a9f632dc8e45aa884f7924ee16f7bf?mtime=1421237274"></script>
```

**Comment by kmillet** [comment]
Er komt een nieuwe banner. Ik vraag na aan Margot of er hiervoor een andere embed code is.

**Comment by taeymma** [comment]
refs https://github.com/OnroerendErfgoed/erkenningen/issues/27

**Comment by kmillet** [comment]
De embedded code die ik kreeg van Margot, stemt overeen met die van Bram. Kan je nog eens testen of die werkt?

**Comment by taeymma** [comment]
Die werkt ja, maar niet met correcte inspringingen, die code heb ik zelf toegevoegd in pyoes.

**Comment by taeymma** [comment]
Volgens @TOM-VC zouden dit 'witte' banners moeten worden.. Zijn deze scriptlinks reeds aangevraagd ofzo?

**Comment by taeymma** [comment]
bump @kmillet

**Comment by kmillet** [comment]
Ik moet eens testen wat er op https://overheid.vlaanderen.be/webuniversum/een-widget-toevoegen-aan-uw-website staat. Ik zou in onze toepassingen liever de 'server side include' gebruiken. Maar ik heb het gevoel dat er nog wat technische info ontbreekt :).

**Comment by kmillet** [comment]
Op https://github.com/OnroerendErfgoed/portaalwebsite/issues/2 kan je de embedcodes overigens vinden en de link naar info over het aanpassen van margin en breakpoints.

**Comment by taeymma** [comment]
> U krijgt van ons een 'embed code' nadat u een Global header en footer of Hulpwidget aanvroeg. 

Aangevraagd ook?

**Comment by taeymma** [comment]
hmm.. ziet er nie echt zo schoon uit.. wat denk jij @TOM-VC?

![screenshot_inv_nieve_banners](https://user-images.githubusercontent.com/10401895/37714317-8c7b8efc-2d19-11e8-985f-34b4d961192f.png)

**Comment by kmillet** [comment]
Tja, die beheerskanten zijn nu ook wel niet helemaal volgens de huisstijl. Daarom vloekt dat idd een beetje.

**Comment by taeymma** [comment]
https://doc.onroerenderfgoed.be/docs/inventaris_2.0/fa_inventaris/inventaris_erfgoedobjecten.html

**Comment by goessebr** [comment]
@kmillet en @TOM-VC , bekijken jullie dit nog eens?

**Comment by kmillet** [comment]
Ik denk dat de banner in principe wegmag bij interne toepassingen. Voor externe toepassingen moet het eigenlijk wel in de huisstijl zijn. @TOM-VC kan jij een ontwerp maken dat rekening houdt met die nieuwe banner?

**Comment by cedrikv** [comment]
Voor inventaris heb ik een apart ticket aangemaakt:
https://github.com/OnroerendErfgoed/inventaris/issues/257

**Comment by cedrikv** [comment]
Deze mag dan toe van mij
