### ISSUE TITLE
Foto uit header komt bij brede schermen links onder het logo uit

### ISSUE THREAD

**Issue by maarten-vermeyen** [OnroerendErfgoed/pyoes#93]
![screenshot from 2016-07-14 13-07-08](https://cloud.githubusercontent.com/assets/1158362/16837608/8d23abbc-49c4-11e6-9a93-2087e613f769.png)

**Comment by taeymma** [comment]
Dit moet specifiek in elke app opgelost worden. Code is voorzien in pyoes sinds 0.4.4.

**Comment by taeymma** [comment]
Ik zal het al aanpassen in beheersplannen.
